export const courseSeeds = [
    {
        "name": "Etica în îngrijiri paliative",
        "shortDescription": "Cursul este recomandat CUI?",
        "description": 'La sfârşitul modulului asistenții medicali vor fi capabili:"\n\r"• Să reflecteze asupra unor situaţii în care au apelat la principiile etice medicale"\n\r"• Să reflecteze la beneficiul cunoaşterii şi aplicării principiilor etice medicale"\n\r"• Să reflecteze asupra implicării problemelor de etică în orice decizie medicală"\n\r""\n\r"• Să definească etica"\n\r"• Să enumere cele 4 principii etice medicale"\n\r"• Să descrie aplicarea regulilor etice în îngrijirile paliative"\n\r"• Să enumere 3 modele de relaţie personal medical-pacient"\n\r"• Să descrie procesul de luare a deciziilor de tratament la pacienţii cu boli în stadiu avansat"\n\r""\n\r"• Să demonstreze abilitatea de a se folosi de principiile etice teoretice în luare de decizii clinice"\n\r"• Să demonstreze abilitatea de a rezolva dileme etice"\n\r"• Să demonstreze abilitatea de analiză a diferitelor relaţii personal medical-pacient',
        "accessDays": 21,
        "authors": "-",
        "courseRole": "MULTI_DISCIPLINARY",
        "courseState": "PUBLISHED",
        "courseType": "ALWAYS_ON",
        "credits": 0,
        "price": 100,
        "currency": "RON",
        "startDate": "2021-06-09",
        "endDate": "2021-12-31",
        "hours": 8,
        "image": "https://studiipaliative.odoo.com/web/image/slide.channel/9/image_1920/Introducere%20%C3%AEn%20%C3%AEngrijire%20paliativ%C4%83%20%2812%20ore%29?unique=0d0bcc4",
    },
    {
        "name": "Introducere în îngrijire paliativă",
        "shortDescription": "Majoritatea dintre noi am fost confruntaţi cu nevoia de a îngriji un pacient suferind de o boală incurabilă avansată. Am constatat atunci că experienţa şi cunoştinţele profesionale nu ne ajută în suficientă măsură...",
        "description": "<p>Foarte probabil că majoritatea dintre noi am fost confruntaţi, în practica clinică sau în viaţa de familie, cu nevoia de a îngriji un pacient suferind de o boală incurabilă avansată. Am constatat atunci că experienţa şi cunoştinţele profesionale nu ne ajută în suficientă măsură pentru a asigura o îngrijire de calitate sub toate aspectele. Îngrijirea paliativă oferă răspunsuri în astfel de situaţii.</p><p>Cursul este recomandat tuturor celor care doresc să se familiarizeze cu ceea ce înseamnă îngrijirea paliativă, cu modul de abordare holistică a pacientului, să demonteze mituri despre îngrijirea paliativă și să cunoască toate categoriile de pacienți care pot beneficia de aceasta, precum și nivelurile si tipurile de servicii de paliație.</p><p>Accesul la curs este de maxim 3 săptămâni, timp în care parcurgerea celor 12 ore de curs poate fi planificată într-un ritm adaptat fiecărui cursant în parte.</p><p>De pe un PC cu monitor mare cursul poate fi urmărit cel mai bine dar platforma este adaptată și pentru laptop sau smartphone.</p><p>Vă recomandăm să aveți la îndemână hârtie și creion pentru a rezolva exercițiile propuse în sesiuni.</p><p>Evaluarile de la început și de pe parcurs au menirea să vă trezească curiozitatea pentru subiectele care vor fi atinse și în egală măsură să vă motiveze să parcurgeți fiecare sesiune în parte pentru ca la final să vă bucurați de îmbunățirea cunoștințelor în îngrijiri paliative. Testul final poate fi parcurs în 30 de minute, iar pentru a obține CERTIFICATUL DE ABSOLVIRE trebuie să obțineți punctajul minim de 75% (din două încercări).</p><p>Acest curs a fost pregătit pentru Dvs. de HOSPICE Casa Speranței ©2020- Mălina Dumitrescu- formator cu experiență de peste 28 de ani ca trainer și manager de servicii de paliație. Corina Dobă- revizuire sesiuni, Laura Iosub- suport tehnic (cshospice@hospice.ro, 0728 130081).</p>",
        "accessDays": 21,
        "authors": "Mălina Dumitrescu- formator cu experiență de peste 28 de ani ca trainer și manager de servicii de paliație. Corina Dobă- revizuire sesiuni, Laura Iosub- suport tehnic",
        "courseRole": "MEDICAL",
        "courseState": "PUBLISHED",
        "courseType": "ALWAYS_ON",
        "credits": 10,
        "price": 150,
        "currency": "RON",
        "startDate": "2021-06-09",
        "endDate": "2021-12-31",
        "hours": 12,
        "image": "https://studiipaliative.odoo.com/web/image/slide.channel/9/image_1920/Introducere%20%C3%AEn%20%C3%AEngrijire%20paliativ%C4%83%20%2812%20ore%29?unique=0d0bcc4",
    },
    {
        "name": "Îngrijiri paliative de bază 1",
        "shortDescription": "Cursul este recomandat asistenților medicali care doresc să inițieze instruirea în vederea obținerii certificatului de 36 ore EMC în îngrijire paliativă și celor care au nevoie să acumuleze un număr de 120 ore EMC în îngrijire paliativă.",
        "description": "<p>Cursul este recomandat atât asistenților medicali care doresc să inițieze instruirea în vederea obținerii certificatului de 36 ore EMC în îngrijire paliativă- care le permite să practice îngrijiri paliative de bază cât și asistenților medicali cu experiență clinică în paliație de minim 3 ani de zile dar care au nevoie să acumuleze un număr de 120 ore EMC în îngrijire paliativă.</p><p>Accesul la curs este de maxim 3 săptămâni, timp în care parcurgerea celor 12 ore de curs poate fi planificată într-un ritm adaptat fiecărui cursant în parte</p><p>De pe un PC cu monitor mare cursul poate fi urmărit cel mai bine dar platforma este adaptată și pentru laptop sau smartphone.</p><p>Vă recomandăm să aveți la îndemână hârtie și creion pentru a rezolva exercițiile propuse în sesiuni.</p>",
        "accessDays": 21,
        "authors": "As. Univ. Dr. Nicoleta Mitrea, As. Med. Lic. Camelia Ancuța - asistente medicale cu experiență de peste 15 ani ca traineri dar și în practica clinică în servicii de paliație, Corina Dobă - revizuire sesiuni, Laura Iosub - suport tehnic",
        "courseRole": "MEDICAL",
        "courseState": "PUBLISHED",
        "courseType": "ALWAYS_ON",
        "credits": 10,
        "price": 150,
        "currency": "RON",
        "startDate": "2021-06-09",
        "endDate": "2021-12-31",
        "hours": 12,
        "image": "https://studiipaliative.odoo.com/web/image/slide.channel/7/image_1920/%C3%8Engrijiri%20paliative%20de%20baz%C4%83%201%20%2812%20ore%29?unique=e1765fe",
    },
    {
        "name": "Îngrijiri paliative de bază 2",
        "shortDescription": "Cursul este recomandat asistenților medicali care doresc să inițieze instruirea în vederea obținerii certificatului de 36 ore EMC în îngrijire paliativă și celor care au nevoie să acumuleze un număr de 120 ore EMC în îngrijire paliativă.",
        "description": "<p>Cursul este recomandat atât asistenților medicali care doresc să inițieze instruirea în vederea obținerii certificatului de 36 ore EMC în îngrijire paliativă- care le permite să practice îngrijiri paliative de bază cât și asistenților medicali cu experiență clinică în paliație de minim 3 ani de zile dar care au nevoie să acumuleze un număr de 120 ore EMC în îngrijire paliativă.</p><p>Asistenții medicali cu Curs introductiv de îngrijiri paliative AMI- 24 ore (efectuat față către față, pănă în martie 2020) se înscriu direct la INGRIJIRI PALIATIVE DE BAZA 2 (12 ore)</p><p>Accesul la curs este de maxim 3 săptămâni, timp în care parcurgerea celor 12 ore de curs poate fi planificată într-un ritm adaptat fiecărui cursant în parte</p><p>De pe un PC cu monitor mare cursul poate fi urmărit cel mai bine dar platforma este adaptată și pentru laptop sau smartphone.</p><p>Vă recomandăm să aveți la îndemână hârtie și creion pentru a rezolva exercițiile propuse în sesiuni.</p><p>Pentru testul final de certificare trebuie sa răspundeți corect la cel puțin 75% din cele 20 de întrebări. Aveti 20 minute la dispozitie.</p>",
        "accessDays": 21,
        "authors": "As. Univ. Dr. Nicoleta Mitrea, As. Med. Lic. Camelia Ancuța, Psih. Doina Găman - profesioniști cu experiență de peste 15 ani ca traineri dar și în practica clinică în servicii de paliație. Sorina Hasu- revizuire sesiuni, Laura Iosub- suport tehnic",
        "courseRole": "MEDICAL",
        "courseState": "PUBLISHED",
        "courseType": "ALWAYS_ON",
        "credits": 10,
        "price": 150,
        "currency": "RON",
        "startDate": "2021-06-09",
        "endDate": "2021-12-31",
        "hours": 12,
        "image": "https://studiipaliative.odoo.com/web/image/slide.channel/21/image_1920/%C3%8Engrijiri%20paliative%20de%20baz%C4%83%202%20%2812%20ore%29?unique=a519b96",
    },
    {
        "name": "Practici avansate în îngrijiri paliative",
        "shortDescription": "Curs dedicat exclusiv membrilor echipei interdisciplinare de ingrijiri paliative (asistenți sociali, psihologi, terapeuți, clerici, alt personal)",
        "description": 'Curs dedicat exclusiv membrilor echipei interdisciplinare de ingrijiri paliative (asistenți sociali, psihologi, terapeuți, clerici, alt personal), care au finalizat in format fata catre fata primul modul de 24 de ore al Programului modular aprofundat de 60 de ore. Durata de parcurgere a cursului este de 4 saptamani"\n\r""\n\r\"Conditii de obtinere a certificatului:"\n\r"- participarea la cele 4 intalniri online cu lectorul (14:00-16:00, incepand cu 17 septembrie 2020- zoom1)"\n\r"- pregatirea si trimiterea pana la termenul limita a unei REFLECTII asupra unui pacient (prezentare caz- zoom 4)"\n\r"- finalizarea a minim 80% din testul grila final (20 intrebari in 30 minute, o singura incerare disponibila)"\n\r""\n\r"De pe un PC cu monitor mare cursul poate fi urmărit cel mai bine dar platforma este adaptată și pentru laptop sau smartphone."\n\r"Vă recomandăm să aveți la îndemână hârtie și creion pentru a rezolva exercițiile propuse în sesiuni."\n\r""\n\r"Acest curs a fost pregătit pentru Dvs. de HOSPICE Casa Speranței ©2020- Psiholog Doina Găman- formator cu experiență în servicii de paliație. Corina Dobă și Sorina Hașu- revizuire sesiuni, Laura Iosub- suport tehnic (0728 130081, L-V 9:00-17:00)."\n\r"',
        "accessDays": 28,
        "authors": "Psiholog Doina Găman - formator cu experiență în servicii de paliație, Corina Dobă și Sorina Hașu - revizuire sesiuni, Laura Iosub - suport tehnic",
        "courseRole": "MULTI_DISCIPLINARY",
        "courseState": "PUBLISHED",
        "courseType": "ALWAYS_ON",
        "credits": 0,
        "price": 250,
        "currency": "RON",
        "startDate": "2021-06-09",
        "endDate": "2021-12-31",
        "hours": 36,
        "image": "https://studiipaliative.odoo.com/web/image/slide.channel/20/image_1920/Practici%20avansate%20%C3%AEn%20%C3%AEngrijiri%20paliative%20%2836%20ore%29?unique=fd65884",
    },
    {
        "name": "Îngrijiri paliative pentru echipa interdisciplinara",
        "shortDescription": "Curs dedicat membrilor echipei interdisciplinare de ingrijiri paliative. Durata de parcurgere a cursului este de 11 saptamani.",
        "description": "Curs dedicat membrilor echipei interdisciplinare de ingrijiri paliative. Durata de parcurgere a cursului este de 11 saptamani. Conditii de obtinere a certificatului: - finalizarea a minim 80% din testul grila final (20 intrebari in 30 minute)- participarea la toate cele 6 intalniri ZOOM cu lectorul- pregatirea si trimiterea pana in saptamana a 10-a a unei REFLECTII asupra unui pacienti. De pe un PC cu monitor mare cursul poate fi urmărit cel mai bine dar platforma este adaptată și pentru laptop sau smartphone. Vă recomandăm să aveți la îndemână hârtie și creion pentru a rezolva exercițiile propuse în sesiuni. Acest curs a fost pregătit pentru Dvs. de HOSPICE Casa Speranței ©2020- Psiholog Doina Găman- formator cu experiență în servicii de paliație, Mălina Dumitrescu- formator cu experiență de peste 28 de ani ca trainer și manager de servicii de paliație, As. Univ. Dr. Nicoleta Mitrea, As. Med. Lic. Camelia Ancuța- asistente medicale cu experiență de peste 15 ani ca traineri dar și în practica clinică în servicii de paliație. Corina Dobă și Sorina Hașu- revizuire sesiuni, Laura Iosub- suport tehnic (0728 130081, L-V 9:00-17:00).",
        "accessDays": 77,
        "authors": "Psiholog Doina Găman - formator cu experiență în servicii de paliație, Corina Dobă și Sorina Hașu - revizuire sesiuni, Laura Iosub - suport tehnic",
        "courseRole": "MULTI_DISCIPLINARY",
        "courseState": "PUBLISHED",
        "courseType": "ALWAYS_ON",
        "credits": 0,
        "price": 500,
        "currency": "RON",
        "startDate": "2021-06-09",
        "endDate": "2021-12-31",
        "hours": 60,
        "image": "https://studiipaliative.odoo.com/web/image/slide.channel/24/image_1920/%C3%8Engrijiri%20paliative%20pentru%20echipa%20interdisciplinara%20%2860%20ore%29?unique=8be388a",
    }
];